jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin 
         name: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
credentials:
  system:
    domainCredentials:
      - credentials:
         - usernamePassword:
              scope: GLOBAL
              id: "docker"
              username: "${DOCKER_USER}"
              password: "${DOCKER_USER_PASSWORD}"
              description: "Username/Password Credentials for DockerRegistry"
         - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "web"
              username: "web"
              description: "SSH with private key file. Private key provided"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:${SSH_PRIVATE_FILE_PATH}}" # Path to file loaded from Environment Variable
unclassified:
  location:
    url: http://127.0.0.:8080/
jobs:
  - script: >
      pipelineJob('testJob') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/eadg1/testWeb' }
                        branch '*/docker-master'
                        extensions {}
                    }
                    }
                   triggers
                   {
                   scm('H/2 * * * *')
                   }    
                  }
              }
          }
      
