version: "3.4"
services:
  jenkins-server:
    hostname: jenkinsserver
    build:
      context: ./
      dockerfile: ./Dockerfile

    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5000:5000"
    env_file:
    - .env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - ./secrets:/keys