---
- hosts: all
  become: true
  roles:
    - docker
    - docker-compose
  tasks:
  - name: Install for apt via  HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      
      
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
 
  - name: Give insecure permissions to an existing file
    file:
      path: /var/run/docker.sock
      mode: '0666'
