---
- hosts: all
  become: true
  tasks:
  - name: Create web user
    user:
     name: web
     shell: /bin/bash
  - name: Add authorized keys
    authorized_key:
       user: web
       key:   "{{ lookup('file', 'docker/secrets/key.pub') }}"

  - name: Make sure we have a 'deployers' group
    group:
     name: deployers
     state: present

  - name: Allow 'deployers' passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%deployers'
      line: '%deployers ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  - name: Add sudoers
    user:
      name=web
      groups=deployers
      append=yes
      
  - name: Install for apt via  HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      
  - name: Add an apt  gpg key for docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: install docker and  deps
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - python3-docker
      - python3-requests
    notify:
      - docker status
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
 
  handlers:
    - name: docker status
      service: name=docker state=started
