---
- hosts: all
  become: true
  roles:
   - docker
  tasks:
  - name: Create web user
    user:
     name: web
     shell: /bin/bash
  - name: Add authorized keys
    authorized_key:
       user: web
       key:   "{{ lookup('file', 'docker/secrets/key.pub') }}"

  - name: Make sure we have a 'deployers' group
    group:
     name: deployers
     state: present

  - name: Allow 'deployers' passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%deployers'
      line: '%deployers ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  - name: Add sudoers
    user:
      name=web
      groups=deployers
      append=yes
      
  - name: Install for apt via  HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
 
